services:
    simple-aes:
      build: .
      ports:
        - 7500:8080
      container_name: idk
      restart: on-failure
      deploy:
        resources:
          limits:
            cpus: '0.25'
            memory: 256M